name: CICD
on: 
  push:
    branches: main
  pull_request:
    branches: main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Setup Go Environment
        uses: actions/setup-go@v6.0.0

      - name: Install dependencies
        run: go mod tidy

      - name: Build
        run: go build main.go

      - name: Test
        run: go test -v
